project:
  type: website  # or blog if you're building a blog

website:
  title: "today"
  navbar:
    left:
      - href: hello.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# Optional: Specify output format
output:
  html:
    embed-resources: true  # Embed resources for easier deployment

# Optional: Include any additional configuration settings for navigation, theme, etc.
