name: Quarto Publish

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js (use Node.js 20)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Quarto
        run: |
          sudo apt-get install gdebi-core
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.340/quarto-1.3.340-linux-amd64.deb
          sudo gdebi --non-interactive quarto-1.3.340-linux-amd64.deb

      - name: Install Python Dependencies
        run: |
          python3 -m pip install jupyter nbformat

      - name: Render the Quarto site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
